### ISSUE TITLE
servo example fails

### ISSUE THREAD

**Issue by zankich** [hybridgroup/cylon-beaglebone#24]
The [servo](https://github.com/hybridgroup/cylon-beaglebone/blob/34b320c602d9d358d7de8aee6194c4386811d4dc/examples/servo/servo.js) fails with this output

```
root@beaglebone:/tmp/cylon# node servo.js
I, [2014-12-23T21:58:33.796Z]  INFO -- : Initializing connections.
I, [2014-12-23T21:58:35.539Z]  INFO -- : Initializing devices.
I, [2014-12-23T21:58:35.562Z]  INFO -- : Starting connections.
I, [2014-12-23T21:58:35.571Z]  INFO -- : Starting devices.
I, [2014-12-23T21:58:35.575Z]  INFO -- : Working.

TypeError: Object #<Object> has no method 'push'
    at Beaglebone.servoWrite (/tmp/cylon/node_modules/cylon-beaglebone/lib/beaglebone.js:242:13)
    at Servo.angle (/tmp/cylon/node_modules/cylon-gpio/lib/servo.js:60:19)
    at null.<anonymous> (/tmp/cylon/servo.js:43:16)
    at wrapper [as _onTimeout] (timers.js:252:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```
I'm running node version 

```
root@beaglebone:/tmp/cylon# node -v
v0.10.25
```

and debian version
```
root@beaglebone:/tmp/cylon# cat /etc/debian_version
7.7
```

and here is the output of my installed node modules
```
root@beaglebone:/tmp/cylon# npm ls
cylon@0.0.0 /tmp/cylon
├─┬ cylon@0.21.2
│ ├── async@0.9.0
│ ├─┬ body-parser@1.9.0
│ │ ├── bytes@1.0.0
│ │ ├── depd@1.0.0
│ │ ├── iconv-lite@0.4.4
│ │ ├── media-typer@0.3.0
│ │ ├─┬ on-finished@2.1.0
│ │ │ └── ee-first@1.0.5
│ │ ├── qs@2.2.4
│ │ ├── raw-body@1.3.0
│ │ └─┬ type-is@1.5.4
│ │   └─┬ mime-types@2.0.4
│ │     └── mime-db@1.3.1
│ ├─┬ express@4.9.8
│ │ ├─┬ accepts@1.1.4
│ │ │ ├─┬ mime-types@2.0.4
│ │ │ │ └── mime-db@1.3.1
│ │ │ └── negotiator@0.4.9
│ │ ├── cookie@0.1.2
│ │ ├── cookie-signature@1.0.5
│ │ ├─┬ debug@2.0.0
│ │ │ └── ms@0.6.2
│ │ ├── depd@0.4.5
│ │ ├── escape-html@1.0.1
│ │ ├─┬ etag@1.4.0
│ │ │ └── crc@3.0.0
│ │ ├── finalhandler@0.2.0
│ │ ├── fresh@0.2.4
│ │ ├── media-typer@0.3.0
│ │ ├── merge-descriptors@0.0.2
│ │ ├── methods@1.1.0
│ │ ├─┬ on-finished@2.1.1
│ │ │ └── ee-first@1.1.0
│ │ ├── parseurl@1.3.0
│ │ ├── path-to-regexp@0.1.3
│ │ ├─┬ proxy-addr@1.0.4
│ │ │ ├── forwarded@0.1.0
│ │ │ └── ipaddr.js@0.1.5
│ │ ├── qs@2.2.4
│ │ ├── range-parser@1.0.2
│ │ ├─┬ send@0.9.3
│ │ │ ├── destroy@1.0.3
│ │ │ ├── mime@1.2.11
│ │ │ ├── ms@0.6.2
│ │ │ └─┬ on-finished@2.1.0
│ │ │   └── ee-first@1.0.5
│ │ ├── serve-static@1.6.4
│ │ ├─┬ type-is@1.5.4
│ │ │ └─┬ mime-types@2.0.4
│ │ │   └── mime-db@1.3.1
│ │ ├── utils-merge@1.0.0
│ │ └── vary@1.0.0
│ └── robeaux@0.3.0
├─┬ cylon-beaglebone@0.13.0
│ ├─┬ cylon@0.21.2
│ │ ├── async@0.9.0
│ │ ├─┬ body-parser@1.9.0
│ │ │ ├── bytes@1.0.0
│ │ │ ├── depd@1.0.0
│ │ │ ├── iconv-lite@0.4.4
│ │ │ ├── media-typer@0.3.0
│ │ │ ├─┬ on-finished@2.1.0
│ │ │ │ └── ee-first@1.0.5
│ │ │ ├── qs@2.2.4
│ │ │ ├── raw-body@1.3.0
│ │ │ └─┬ type-is@1.5.4
│ │ │   └─┬ mime-types@2.0.4
│ │ │     └── mime-db@1.3.1
│ │ ├─┬ express@4.9.8
│ │ │ ├─┬ accepts@1.1.4
│ │ │ │ ├─┬ mime-types@2.0.4
│ │ │ │ │ └── mime-db@1.3.1
│ │ │ │ └── negotiator@0.4.9
│ │ │ ├── cookie@0.1.2
│ │ │ ├── cookie-signature@1.0.5
│ │ │ ├─┬ debug@2.0.0
│ │ │ │ └── ms@0.6.2
│ │ │ ├── depd@0.4.5
│ │ │ ├── escape-html@1.0.1
│ │ │ ├─┬ etag@1.4.0
│ │ │ │ └── crc@3.0.0
│ │ │ ├── finalhandler@0.2.0
│ │ │ ├── fresh@0.2.4
│ │ │ ├── media-typer@0.3.0
│ │ │ ├── merge-descriptors@0.0.2
│ │ │ ├── methods@1.1.0
│ │ │ ├─┬ on-finished@2.1.1
│ │ │ │ └── ee-first@1.1.0
│ │ │ ├── parseurl@1.3.0
│ │ │ ├── path-to-regexp@0.1.3
│ │ │ ├─┬ proxy-addr@1.0.4
│ │ │ │ ├── forwarded@0.1.0
│ │ │ │ └── ipaddr.js@0.1.5
│ │ │ ├── qs@2.2.4
│ │ │ ├── range-parser@1.0.2
│ │ │ ├─┬ send@0.9.3
│ │ │ │ ├── destroy@1.0.3
│ │ │ │ ├── mime@1.2.11
│ │ │ │ ├── ms@0.6.2
│ │ │ │ └─┬ on-finished@2.1.0
│ │ │ │   └── ee-first@1.0.5
│ │ │ ├── serve-static@1.6.4
│ │ │ ├─┬ type-is@1.5.4
│ │ │ │ └─┬ mime-types@2.0.4
│ │ │ │   └── mime-db@1.3.1
│ │ │ ├── utils-merge@1.0.0
│ │ │ └── vary@1.0.0
│ │ └── robeaux@0.3.0
│ ├── cylon-gpio@0.21.0
│ ├── cylon-i2c@0.18.0
│ └─┬ i2c@0.1.6
│   ├── bindings@1.1.1
│   ├── coffee-script@1.3.3
│   ├── repl@0.1.3
│   └── underscore@1.2.4
├── cylon-gpio@0.21.0
└── cylon-i2c@0.18.0
```

**Comment by edgarsilva** [comment]
This has been fixed and released. Closing now.
