### ISSUE TITLE
Can't seem to get servos working on BBB

### ISSUE THREAD

**Issue by mhelmetag** [hybridgroup/cylon-beaglebone#36]
Hey, there!

I seem to be having some trouble getting servos to work on my BBB. It looks like `this._ocpDir()` on [this line](https://github.com/hybridgroup/cylon-beaglebone/blob/master/lib/pwm-pin.js#L121) is undefined instead of being a string or buffer.

I was able to flash and LED with no problem.

Here's my system info:

```
debian@arm:~/projects/servo$ uname -a
Linux arm 4.4.12-ti-r30 #1 SMP Wed Jun 8 20:29:06 UTC 2016 armv7l GNU/Linux
debian@arm:~/projects/servo$ cat /etc/debian_version 
8.6
debian@arm:~/projects/servo$ npm --version
3.10.3
debian@arm:~/projects/servo$ nodejs --version
v6.6.0
```

I'm trying to run this:

``` javascript
var Cylon = require('cylon');

Cylon.robot({
  connections: {
    beaglebone: { adaptor: 'beaglebone' }
  },

  devices: {
    servo: {
      driver: 'servo',
      pin: 'P8_7',
      freq: 50,
      pulseWidth: { min: 500, max: 2400 },
      limits: { bottom: 20, top: 160 }
    }
  },

  work: function(my) {
    var angle = 30,
        increment = 40;

    every((1).seconds(), function() {
      angle += increment;

      my.servo.angle(angle);

      console.log("Current Angle: " + my.servo.currentAngle());

      if ((angle === 30) || (angle === 150)) { increment = -increment; }
    });
  }
}).start();
```

Here's the stacktrace:

```
debian@arm:~/projects/servo$ sudo nodejs index.js 
2016-09-27T07:49:22.777Z : [Robot 1] - Starting connections.
2016-09-27T07:49:22.871Z : [Robot 1] - Starting connection 'beaglebone'.
2016-09-27T07:49:22.881Z : [Robot 1] - Starting devices.
2016-09-27T07:49:22.885Z : [Robot 1] - Starting device 'servo' on pin P8_7.
2016-09-27T07:49:22.886Z : [Robot 1] - Working.
fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

TypeError: path must be a string or Buffer
  at TypeError (native)
  at Object.fs.readdirSync (fs.js:951:18)
  at PwmPin.Pin._findFile (/home/debian/projects/servo/node_modules/cylon-beaglebone/lib/pin.js:16:18)
  at PwmPin._pwmDir (/home/debian/projects/servo/node_modules/cylon-beaglebone/lib/pwm-pin.js:121:16)
  at PwmPin.connect (/home/debian/projects/servo/node_modules/cylon-beaglebone/lib/pwm-pin.js:59:30)
  at Beaglebone._pwmWrite (/home/debian/projects/servo/node_modules/cylon-beaglebone/lib/beaglebone.js:316:9)
  at Beaglebone.pwmWrite (/home/debian/projects/servo/node_modules/cylon-beaglebone/lib/beaglebone.js:339:8)
  at Beaglebone.servoWrite (/home/debian/projects/servo/node_modules/cylon-beaglebone/lib/beaglebone.js:354:8)
  at Servo.angle (/home/debian/projects/servo/node_modules/cylon-gpio/lib/servo.js:102:19)
  at Timeout._repeat (/home/debian/projects/servo/index.js:25:16)
  at Timeout.wrapper [as _onTimeout] (timers.js:425:11)
  at tryOnTimeout (timers.js:232:11)
  at Timer.listOnTimeout (timers.js:202:5)
```

I'm chugging along with `node debug` but any help would be appreciated.

**Comment by mhelmetag** [comment]
Actually it looks like this is because I don't have `/sys/devices/ocp`...

Update: It's because I have `/sys/devices/platform/ocp`. This might be non standard as I'm using an image from the eLinux BBB site.

Update 2: Yeah, none of the files in `/sys/devices/platform/ocp` look right as nothing closely resembles `/^ocp\.\d+$/` in there. I'm going to try the standard image and see what happens.

Update 3: I tried another image off of [beagleboard](https://beagleboard.org/latest-images) and seem to be closer but my ocp files are split by `:`s instead of `.`s. So my regex would be more like `/^ocp\:\d+$/`.

**Comment by mhelmetag** [comment]
It's because I have `/sys/devices/platform/ocp`. This might be non standard as I'm using an image from the eLinux BBB site.

**Comment by mhelmetag** [comment]
Ah well I'm going to close this  and say that it looks like cylon.js just doesn't really work with newer versions of the Beaglebone's debian (without some modification). On the other hand, Raspian (Raspberry Pi's debian) work perfectly so I'll be using that with cylon.
